// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRp5LS5pcidqtBgvoBabfAD_bfqNUfdi0',
    appId: '1:796486737000:web:76e8cb09f2360ad8e32fdd',
    messagingSenderId: '796486737000',
    projectId: 'flutter-auth-app-6d6cb',
    authDomain: 'flutter-auth-app-6d6cb.firebaseapp.com',
    storageBucket: 'flutter-auth-app-6d6cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6m8VUQg5pSU4pDvdDwbXo74JJjpPkrY0',
    appId: '1:796486737000:android:f0485656f4137426e32fdd',
    messagingSenderId: '796486737000',
    projectId: 'flutter-auth-app-6d6cb',
    storageBucket: 'flutter-auth-app-6d6cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABStXTRhxR8QeAxH8GpUNGutf8CrgjxFM',
    appId: '1:796486737000:ios:c5ba8137ff48e7f8e32fdd',
    messagingSenderId: '796486737000',
    projectId: 'flutter-auth-app-6d6cb',
    storageBucket: 'flutter-auth-app-6d6cb.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABStXTRhxR8QeAxH8GpUNGutf8CrgjxFM',
    appId: '1:796486737000:ios:c5ba8137ff48e7f8e32fdd',
    messagingSenderId: '796486737000',
    projectId: 'flutter-auth-app-6d6cb',
    storageBucket: 'flutter-auth-app-6d6cb.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRp5LS5pcidqtBgvoBabfAD_bfqNUfdi0',
    appId: '1:796486737000:web:724bbc97095a79cae32fdd',
    messagingSenderId: '796486737000',
    projectId: 'flutter-auth-app-6d6cb',
    authDomain: 'flutter-auth-app-6d6cb.firebaseapp.com',
    storageBucket: 'flutter-auth-app-6d6cb.firebasestorage.app',
  );
}
